# Generated by Django 4.2.6 on 2024-07-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_escuela_materia_promediocalificaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
    ]
