# Generated by Django 4.2.6 on 2024-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usuario_apellidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionescuantitativas',
            name='pregunta_10',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacionescuantitativas',
            name='pregunta_11',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacionescuantitativas',
            name='pregunta_12',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacionescuantitativas',
            name='pregunta_13',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacionescuantitativas',
            name='pregunta_14',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacionescuantitativas',
            name='pregunta_15',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacionescuantitativas',
            name='pregunta_16',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacionescuantitativas',
            name='pregunta_17',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacionescuantitativas',
            name='pregunta_18',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacionescuantitativas',
            name='pregunta_19',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacionescuantitativas',
            name='pregunta_20',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacionescuantitativas',
            name='pregunta_9',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
