# Generated by Django 4.2.6 on 2024-07-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_calificacionescuantitativas_pregunta_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promediocalificaciones',
            name='prom_pregunta_10',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promediocalificaciones',
            name='prom_pregunta_11',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promediocalificaciones',
            name='prom_pregunta_12',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promediocalificaciones',
            name='prom_pregunta_13',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promediocalificaciones',
            name='prom_pregunta_14',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promediocalificaciones',
            name='prom_pregunta_15',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promediocalificaciones',
            name='prom_pregunta_16',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promediocalificaciones',
            name='prom_pregunta_17',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promediocalificaciones',
            name='prom_pregunta_18',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promediocalificaciones',
            name='prom_pregunta_19',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promediocalificaciones',
            name='prom_pregunta_20',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promediocalificaciones',
            name='prom_pregunta_9',
            field=models.FloatField(default=0),
        ),
    ]
