# Generated by Django 4.2.6 on 2024-07-14 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_promediocalificaciones_prom_pregunta_10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortalezasDebilidadesCuantitativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prom_pregunta_9', models.FloatField(default=0)),
                ('prom_pregunta_10', models.FloatField(default=0)),
                ('prom_pregunta_11', models.FloatField(default=0)),
                ('prom_pregunta_12', models.FloatField(default=0)),
                ('prom_pregunta_13', models.FloatField(default=0)),
                ('prom_pregunta_14', models.FloatField(default=0)),
                ('prom_pregunta_15', models.FloatField(default=0)),
                ('prom_pregunta_16', models.FloatField(default=0)),
                ('prom_pregunta_17', models.FloatField(default=0)),
                ('prom_pregunta_18', models.FloatField(default=0)),
                ('prom_pregunta_19', models.FloatField(default=0)),
                ('prom_pregunta_20', models.FloatField(default=0)),
                ('valoraciones', models.JSONField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fortalezas_debilidades_cuantitativas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
