# Generated by Django 4.2.6 on 2024-07-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fortalezasdebilidadescuantitativas'),
    ]

    operations = [
        migrations.AddField(
            model_name='promediocalificaciones',
            name='codigo_materia',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
