# Generated by Django 4.2.6 on 2024-07-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_promediocalificaciones_codigo_materia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionescualitativas',
            name='comentario_limpio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
