# Generated by Django 4.2.6 on 2024-08-18 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_calificacionescualitativas_comentario_limpio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortalezasDebilidadesCualitativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('valoraciones', models.TextField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fortalezas_debilidades_cualitativas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
