# Generated by Django 4.2.6 on 2024-09-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fortalezasdebilidadescualitativas'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortalezasDebilidadesEscula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('valoraciones', models.TextField()),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fortalezas_debilidades_escuela', to='core.escuela')),
            ],
        ),
    ]
